### PR TITLE
Update Main.js

### PR DESCRIPTION
**Pull request by iamthana**
Hello world with variable.

### CODE REVIEW

**Review by MrKrishnaAgarwal — CHANGES_REQUESTED** [review]
It's not required

**Comment by iamthana** [comment]
Oh sorry, I want to present it differently. I don't see the description as making it seem like it couldn't be done.
Thank.

**Comment by MrKrishnaAgarwal** [comment]
> Oh sorry, I want to present it differently. I don't see the description as making it seem like it couldn't be done.
> Thank.

No worries
I am removing the spam and invalid label

**Comment by iamthana** [comment]
Thank.

**Pull request closed without merging**
